Repository JupyterEverywhere/jupyterlite-extension, pull requests merged in 2025-07, with the labels that each got.

#76 Add a Files widget to upload and view all data files
  src/icons.ts
  src/index.ts
  src/pages/files.tsx
  src/ui-components/FilesWarningBanner.tsx
  style/base.css
  style/files-widget.css
  style/icons/file-icon.svg
  style/icons/image-icon.svg
  style/index.css
  style/index.js
  ui-tests/test-files/a-image.jpg
  ui-tests/test-files/b-dataset.csv
  ui-tests/tests/jupytereverywhere.spec.ts
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/files-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/uploaded-files-grid-chromium-linux.png
Labels: enhancement

#71 Style the share dialog
  src/index.ts
  src/ui-components/share-dialog.tsx
  style/base.css
  ui-tests/tests/jupytereverywhere.spec.ts
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/empty-dialog-over-notebook-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/share-dialog-chromium-linux.png
Labels: enhancement

#89 Add a "Create Copy" button for View Only notebooks, and associated notebook handling
  schema/plugin.json
  src/commands.ts
  src/index.ts
  src/pages/notebook.tsx
  src/view-only.ts
  style/base.css
  ui-tests/tests/jupytereverywhere.spec.ts
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/read-only-notebook-chromium-linux.png
Labels: enhancement

#93 Remove style import from ts file
  src/index.ts
Labels: bug

#94 Align download menu style closer with design
  src/index.ts
  src/ui-components/DownloadDropdownButton.tsx
  style/base.css
  ui-tests/tests/jupytereverywhere.spec.ts
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/download-menu-chromium-linux.png
Labels: enhancement

#113 Try to fix snapshot update job
  .github/workflows/update-integration-tests.yml
Labels: maintenance

#114 Update type definitions for readable IDs
  src/index.ts
  src/sharing-service.ts
Labels: maintenance

#95 Update sizes to match proportions in Figma, scale by 85%
  src/ui-components/PageTitle.tsx
  style/base.css
  style/files-widget.css
  style/icons/download-caret.svg
  style/icons/refresh.svg
  ui-tests/tests/jupytereverywhere.spec.ts
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/application-shell-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/download-menu-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/empty-dialog-over-notebook-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/files-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/read-only-notebook-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/uploaded-files-grid-chromium-linux.png
Labels: enhancement

#111 Add help page
  src/commands.ts
  src/icons.ts
  src/index.ts
  src/pages/help.tsx
  style/help-center.css
  style/icons/help.svg
  style/index.js
  ui-tests/tests/jupytereverywhere.spec.ts
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/application-shell-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/empty-dialog-over-notebook-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/help-chromium-linux.png
Labels: enhancement

#124 Disable context menus for `application-extension`
  lite/jupyter-lite.json
Labels: maintenance

#115 Add the Xeus-R kernel and a kernel switcher
  lite/requirements.txt
  lite/xeus-environment.yml
  package.json
  schema/plugin.json
  src/icons.ts
  src/index.ts
  src/kernels.ts
  src/pages/notebook.tsx
  src/ui-components/KernelSwitcherDropdownButton.tsx
  style/base.css
  style/icons/kernel-caret.svg
  ui-tests/README.md
  ui-tests/tests/jupytereverywhere.spec.ts
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/application-shell-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/empty-dialog-over-notebook-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/kernel-switcher-menu-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/landing-page-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/r-output-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/share-dialog-chromium-linux.png
Labels: enhancement

#125 Conform to PEP639 for license and license metadata
  .pre-commit-config.yaml
  LICENSE
  LICENSE.md
  pyproject.toml
Labels: maintenance

#130 Deploying to Netlify via GitHub Action
  .github/workflows/build.yml
Labels: maintenance

#141 Remove netlify preview on PRs
  .github/workflows/build.yml
Labels: maintenance

#146 Add JE Octopus favicon and change the page title to "Jupyter Everywhere"
  package.json
  static/favicon.ico
  templates/index.html
  ui-tests/tests/jupytereverywhere.spec.ts
Labels: maintenance

#144 Switch to the `xeus-python` kernel
  lite/requirements.txt
  lite/xeus-environment.yml
  src/kernels.ts
  src/landing.tsx
  src/pages/notebook.tsx
  src/ui-components/KernelSwitcherDropdownButton.tsx
  ui-tests/tests/jupytereverywhere.spec.ts
Labels: maintenance

#137 Harden security
  .github/workflows/build.yml
  .github/workflows/check-release.yml
  .github/workflows/enforce-label.yml
  .github/workflows/prep-release.yml
  .github/workflows/publish-release.yml
  .github/workflows/update-integration-tests.yml
  .pre-commit-config.yaml
Labels: maintenance

#152 Replace the JupyterLite loading spinner with a custom JupyterEverywhere spinning indicator
  package.json
  style/base.css
  templates/customise-title-and-spinner.patch
Labels: enhancement

#154 Display a toast notification when switching kernels
  src/index.ts
Labels: enhancement

#151 Add JE branding for contents and settings storage names
  lite/jupyter-lite.json
Labels: maintenance

#161 Split JupyterLite builds into `test` and `prod` jobs
  .github/workflows/build.yml
Labels: maintenance

#162 Fix the artifact name to upload for the Netlify deployment
  .github/workflows/build.yml
Labels: maintenance

#159 Upload notebooks to JupyterEverywhere
  src/landing.tsx
  src/pages/notebook.tsx
  src/upload.ts
  ui-tests/tests/jupytereverywhere.spec.ts
Labels: enhancement

#170 Lint all files
  .github/workflows/build.yml
  .github/workflows/update-integration-tests.yml
  .prettierignore
  package.json
  style/icons/landing/r.svg
  style/icons/landing/testimonial.svg
  templates/customise-title-and-spinner.patch
Labels: maintenance

#168 Include some scientific Python packages as part of the deployment
  lite/xeus-environment.yml
Labels: enhancement

#171 Hide JE tutorial button
  style/landing.css
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/landing-page-chromium-linux.png
Labels: maintenance

#172 Temporarily disable the Competitions and the Help pages from the extension
  src/index.ts
  ui-tests/tests/jupytereverywhere.spec.ts
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/application-shell-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/empty-dialog-over-notebook-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/leave-confirmation-dialog-chromium-linux.png
Labels: maintenance

#169 Add the tidyverse, CourseKata, and neuralnet R packages
  lite/xeus-environment.yml
Labels: enhancement

#174 Update the pages' descriptions with the new JE tagline
  templates/customise-title-and-spinner.patch
  templates/index.html
Labels: enhancement
