Repository JupyterEverywhere/jupyterlite-extension, pull requests merged in 2025-09, with the labels that each got.

#213 Ensure that code cells and Markdown cells have the same height
  style/base.css
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/application-shell-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/empty-dialog-over-notebook-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/leave-confirmation-dialog-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/read-only-notebook-chromium-linux.png
Labels: bug

#216 Disable `@jupyterlab/apputils-extension:state` and add a shim for `@jupyterlab/coreutils:IStateDB`
  lite/jupyter-lite.json
  src/index.ts
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/application-shell-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/empty-dialog-over-notebook-chromium-linux.png
Labels: bug

#214 Hide output execution counts for inactive cells
  style/base.css
  ui-tests/tests/jupytereverywhere.spec.ts
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/multiple-cells-prompt-indicators-chromium-linux.png
Labels: maintenance

#236 Add functionality to delete and download updated data files
  src/pages/files.tsx
  style/base.css
  style/files-widget.css
  ui-tests/tests/jupytereverywhere.spec.ts
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/file-tile-actions-visible-chromium-linux.png
Labels: enhancement

#217 Add an SPA-like route to the Files page via `ILiteRouter`
  package.json
  src/commands.ts
  src/index.ts
  src/pages/competitions.tsx
  src/pages/files.tsx
  src/pages/help.tsx
  src/pages/notebook.tsx
  src/routes.ts
  src/sidebar.ts
  src/ui-components/SidebarIcon.ts
  templates/files-redirect.html
  ui-tests/tests/jupytereverywhere.spec.ts
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/files-full-chromium-linux.png
  yarn.lock
Labels: enhancement

#238 Purge sharing-specific metadata before downloading notebooks as IPyNB files
  src/index.ts
  ui-tests/tests/jupytereverywhere.spec.ts
Labels: bug

#242 Add support for uploading/downloading WEBP images
  src/pages/files.tsx
  src/types/images.d.ts
  ui-tests/test-files/c-flower.webp
  ui-tests/tests/jupytereverywhere.spec.ts
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/uploaded-files-grid-chromium-linux.png
Labels: enhancement

#244 Replace session restart dialog instead of adding a new one
  lite/jupyter-lite.json
  package.json
  schema/plugin.json
  src/dialogs.ts
  src/index.ts
  ui-tests/tests/jupytereverywhere.spec.ts
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/empty-dialog-over-notebook-chromium-linux.png
  yarn.lock
Labels: enhancement
