Repository JupyterEverywhere/jupyterlite-extension, pull requests merged in 2025-06, with the labels that each got.

#38 Add the necessary scaffolding for a custom `MainAreaWidget`
  src/index.ts
  src/view-only/mainarea.ts
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/application-shell-chromium-linux.png
Labels: enhancement

#41 Add minimal styling/application scaffold
  lite/jupyter-lite.json
  src/commands.ts
  src/icons.ts
  src/index.ts
  src/notebook.ts
  src/pages/competitions.tsx
  src/pages/files.tsx
  src/pages/notebook.tsx
  src/types/typings.d.ts
  src/ui-components/DownloadDropdownButton.tsx
  src/ui-components/SidebarIcon.ts
  src/ui-components/share-dialog.tsx
  src/view-only/mainarea.ts
  style/base.css
  style/icons/add.svg
  style/icons/addFile.svg
  style/icons/competition.svg
  style/icons/folder.svg
  style/icons/folderSidebar.svg
  style/icons/link.svg
  style/icons/logo.svg
  style/icons/notebook.svg
  style/icons/save.svg
  ui-tests/tests/jupytereverywhere.spec.ts
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/application-shell-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/files-chromium-linux.png
  yarn.lock
Labels: enhancement

#43 Declare notebook as-read only using save API
  src/pages/notebook.tsx
  ui-tests/tests/jupytereverywhere.spec.ts
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/read-only-notebook-chromium-linux.png
Labels: enhancement

#40 Make passwords non-editable
  src/index.ts
  src/ui-components/share-dialog.tsx
  ui-tests/package.json
  ui-tests/tests/jupytereverywhere.spec.ts
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/share-dialog-chromium-linux.png
  ui-tests/yarn.lock
Labels: maintenance

#48 [FIX] Prevent cursor blinking during playwright tests
  .github/workflows/build.yml
Labels: bug

#45 Quick styling pass
  src/icons.ts
  src/index.ts
  src/pages/notebook.tsx
  src/sidebar.ts
  src/ui-components/SidebarIcon.ts
  style/base.css
  style/icons/fast-forward.svg
  style/icons/refresh.svg
  style/icons/run.svg
  style/icons/stop.svg
  ui-tests/tests/jupytereverywhere.spec.ts
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/application-shell-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/files-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/read-only-notebook-chromium-linux.png
Labels: enhancement

#50 Fix toolbar buttons for notebook
  schema/plugin.json
  src/icons.ts
  src/pages/notebook.tsx
  src/ui-components/DownloadDropdownButton.tsx
  style/icons/download-caret.svg
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/application-shell-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/download-menu-chromium-linux.png
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/read-only-notebook-chromium-linux.png
Labels: bug

#46 Connect saving and sharing notebooks with CKHub API
  src/index.ts
  src/sharing-service.ts
  src/ui-components/share-dialog.tsx
  ui-tests/tests/jupytereverywhere.spec.ts
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/share-dialog-chromium-linux.png
Labels: enhancement

#49 Try to make build faster
  .github/workflows/build.yml
Labels: maintenance

#64 Drop use of passwords from everywhere, and refactor sharing-related code
  src/index.ts
  src/notebook-name.ts
  src/sharing-service.ts
  src/ui-components/share-dialog.tsx
  ui-tests/tests/jupytereverywhere.spec.ts
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/share-dialog-chromium-linux.png
Labels: maintenance

#63 Load notebooks from the CKHub API through their IDs in URL parameters
  src/index.ts
  src/pages/notebook.tsx
  src/sharing-service.ts
  ui-tests/tests/jupytereverywhere.spec.ts-snapshots/read-only-notebook-chromium-linux.png
Labels: enhancement
